name: CredsEncoder
description: CredsEncoder

inputs:
  WORKFLOW_USER:
    description: "Workflow user"
    required: true
  WORKFLOW_USER_PWD:
    description: "Workflow user pwd"
    required: true

outputs:
  ENCODED_BASIC:
    description: "Creds encoded to basic format"
    value: ${{ steps.encode_creds.outputs.ENCODED_BASIC }}

runs:
  using: "composite"
  steps:
    - id: encode_creds
      name: Encode Creds for user ${{ inputs.WORKFLOW_USER }}
      run: |
        ENCODED_BASIC=$(echo -n '${{ inputs.WORKFLOW_USER }}:${{inputs.WORKFLOW_USER_PWD }}' | base64 -w 0)
        echo "ENCODED_BASIC=$ENCODED_BASIC" >> $GITHUB_OUTPUT
      shell: bash
