# This is a basic workflow to help you get started with Actions

name: Automation_CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  trigger_scheduler:
    runs-on: ubuntu-latest
    environment: PreProd
    outputs:
      ENCODED_BASIC: ${{steps.encode_creds.outputs.ENCODED_BASIC}}
    steps:
      - id: encode_creds
        name: Encode Creds for user ${{ vars.KATALON_AUTOMATION_USER }}
        run: |
          ENCODED_BASIC=$(echo -n '${{ vars.KATALON_AUTOMATION_USER }}:${{secrets.KATAlON_AUTOMATION_USER_PWD }}' | base64 -w 0)
          echo "ENCODED_BASIC=$ENCODED_BASIC" >> $GITHUB_OUTPUT
        
      - name: Print Creds 
        run: echo ${{ steps.encode_creds.outputs.ENCODED_BASIC  }}

      - name:  Trigger Katalon schedule with `Default` profile 
        run: |
          curl --request PUT --url https://testops.katalon.io/api/v1/run-configurations/${{vars.JOB_SCHEDULE_ID}}/execute \
          --header 'accept: */*' \
          --header 'authorization: Basic ${{steps.encode_creds.outputs.ENCODED_BASIC }}'


  monitor_scheduler:
    runs-on: ubuntu-latest
    environment: PreProd
    needs: trigger_scheduler
    steps:
      - uses: actions/checkout@v3
      - name: Monitor Schedule `${{vars.JOB_SCHEDULE_ID}} status` 
        run: |
          chmod +x ./scheduler_monitor.sh
          ./scheduler_monitor.sh "${{vars.JOB_SCHEDULE_ID}}" "${{vars.PROJECT_ID }}" "${{needs.trigger_scheduler.outputs.ENCODED_BASIC }}"

  # trigger_katalon:
  #   runs-on: ubuntu-latest
  #   env:
  #     API_KEY: 1420ca43-75b5-427a-8d90-f6e644a892a3
  #   container:
  #     image:  katalonstudio/katalon:8.6.8
    
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         repository: CarlosPintoWindsor/automation
  #         path: automation
  #         ref: master
      
  #     - name: Print working dir
  #       run: |
  #         ls -ll
  #         dir
  #         pwd
  #         ls ${{ github.workspace }}/automation
    
       #run: git clone --branch master https://github.com/krishnatayade/automation_both.git ${{github.workspace}}/automation_both
      #- name: Katalon Studio Github Action
      #  uses: katalon-studio/katalon-studio-github-action@v2.2
      #  continue-on-error: true
      #  with:
      #   version: '8.6.8'
      #   projectPath: '${{ github.workspace }}/automation'
      #   args: '-executionProfile=default -browserType="Chrome"  -testOpsProjectId=1099142 -testSuitePath="Test Suites/Carlos_Desktop_CICD" -apiKey=1420ca43-75b5-427a-8d90-f6e644a892a3 -sendMail=carlosp@windsorstore.com -serverUrl=https://testops.katalon.io --config -webui.autoUpdateDrivers=false -orgId=1132968'
        
      #- name: 'Upload Artifact'
      #  uses: actions/upload-artifact@v3
      #  with:
      #    name: katalon_log
      #    path: /home/runner/.katalon/8.6.8/Katalon_Studio_Engine_Linux_64-8.6.8/configuration/
      #    retention-days: 5

#katalon/scripts/katalonc.sh -noSplash  -retry=0  -runMode=console -executionProfile=default -browserType="Chrome"  -testOpsProjectId=1099142 -projectPath=automation -testSuitePath="Test Suites/Carlos_Desktop_CICD" -apiKey=1420ca43-75b5-427a-8d90-f6e644a892a3 -sendMail=carlosp@windsorstore.com -serverUrl=https://testops.katalon.io --config -webui.autoUpdateDrivers=false -orgId=1132968        

#git clone https://github.com/CarlosPintoWindsor/automation.git automation
#bash ./katalon/scripts/setup.sh

#docker run -v ./katalon:/katalon  --name katalon      -it katalonstudio/katalon:8.6.8 bin/sh   

#/opt/google/chrome/chrome --no-sandbox 

#CHROME_VERSION="119.0.6045.159-1"
#wget --no-verbose -O /tmp/chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_${CHROME_VERSION}_amd64.deb \
#  && apt install -y /tmp/chrome.deb \
#  && rm /tmp/chrome.deb
  
#mkdir chrome
#cd chrome
#wget -oL https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chrome-linux64.zip
#unzip chrome-linux64.zip
#mkdir -p /opt/chrome_temp &&  cp -r chrome-linux64 /opt/chrome_temp/chrome-linux64
#mv /opt/google/chrome /opt/chrome_old
#mkdir -p /opt/google/chrome && mv chrome-linux64/* /opt/google/chrome

#cd /

#mkdir chromedriver
#cd chromedriver
#wget -oL https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/119.0.6045.105/linux64/chromedriver-linux64.zip
#unzip chromedriver-linux64.zip 
#cp chromedriver-linux64.zip /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64.zip
#mv  /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64/ /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64_old
#mv chromedriver-linux64/* /opt/katalonstudio/configuration/resources/drivers/chromedriver_linux64
#cd /